package com.bj.eduteacher.answer.dbhelper;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bj.eduteacher.answer.model.Answer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ANSWER".
*/
public class AnswerDao extends AbstractDao<Answer, Long> {

    public static final String TABLENAME = "ANSWER";

    /**
     * Properties of entity Answer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Shiti_id = new Property(1, int.class, "shiti_id", false, "SHITI_ID");
        public final static Property Daan_teacher = new Property(2, String.class, "daan_teacher", false, "DAAN_TEACHER");
        public final static Property Shiti_ordernum = new Property(3, int.class, "shiti_ordernum", false, "SHITI_ORDERNUM");
    }


    public AnswerDao(DaoConfig config) {
        super(config);
    }
    
    public AnswerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ANSWER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SHITI_ID\" INTEGER NOT NULL ," + // 1: shiti_id
                "\"DAAN_TEACHER\" TEXT," + // 2: daan_teacher
                "\"SHITI_ORDERNUM\" INTEGER NOT NULL );"); // 3: shiti_ordernum
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ANSWER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Answer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getShiti_id());
 
        String daan_teacher = entity.getDaan_teacher();
        if (daan_teacher != null) {
            stmt.bindString(3, daan_teacher);
        }
        stmt.bindLong(4, entity.getShiti_ordernum());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Answer entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getShiti_id());
 
        String daan_teacher = entity.getDaan_teacher();
        if (daan_teacher != null) {
            stmt.bindString(3, daan_teacher);
        }
        stmt.bindLong(4, entity.getShiti_ordernum());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Answer readEntity(Cursor cursor, int offset) {
        Answer entity = new Answer( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // shiti_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // daan_teacher
            cursor.getInt(offset + 3) // shiti_ordernum
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Answer entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShiti_id(cursor.getInt(offset + 1));
        entity.setDaan_teacher(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setShiti_ordernum(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Answer entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Answer entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Answer entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
