package com.bj.eduteacher.answer.dbhelper;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bj.eduteacher.answer.model.Answer;

import com.bj.eduteacher.answer.dbhelper.AnswerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig answerDaoConfig;

    private final AnswerDao answerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        answerDaoConfig = daoConfigMap.get(AnswerDao.class).clone();
        answerDaoConfig.initIdentityScope(type);

        answerDao = new AnswerDao(answerDaoConfig, this);

        registerDao(Answer.class, answerDao);
    }
    
    public void clear() {
        answerDaoConfig.clearIdentityScope();
    }

    public AnswerDao getAnswerDao() {
        return answerDao;
    }

}
